version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/dd-decaf-cfbf6/warehouse-to-model:${IMAGE_TAG:-latest}
    networks:
      default:
      DD-DeCaF:
        aliases:
          - warehouse-to-model
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/warehouse_to_model/wsgi.py
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:*}
      - SENTRY_DSN=${SENTRY_DSN}
      - WAREHOUSE_API=${WAREHOUSE_API:-http://warehouse:8000}
    command: gunicorn -c gunicorn.py warehouse_to_model.wsgi:app

# Additional services that the `web` service `depends_on` should usually only
# be on the default network and not exposed on the general network, i.e.,
# networks:
#   - default

networks:
  DD-DeCaF:
    external: true
